name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "mail-db"
database_id = "eaa89acf-bc5a-43f5-8d7e-262cf9e7084c"

[[kv_namespaces]]
binding = "kv"
id = "6f8b57f5b3ae4ad49312d58a7f53438e"

# 因为没有绑定信用卡所以不用R2，这里必须保持注释(带有#)或者直接删掉
#[[r2_buckets]]
#binding = "r2"
#bucket_name = ""

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
